# Generated by Django 5.0.3 on 2025-09-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='euro_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pound_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
