# Generated by Django 5.0.3 on 2025-09-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_product_euro_rate_remove_product_pound_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='australian_dollar',
        ),
    ]
