# Generated by Django 5.0.3 on 2025-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_remove_product_australian_dollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aud_rate',
            new_name='euro_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='us_dollar',
        ),
    ]
