# Generated by Django 5.0.3 on 2025-09-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_rename_aud_rate_product_euro_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_code', models.CharField(max_length=255)),
                ('child_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_links', to='Dashboard.image')),
            ],
            options={
                'indexes': [models.Index(fields=['parent_code', 'child_code'], name='Dashboard_p_parent__febf19_idx')],
                'unique_together': {('image', 'parent_code', 'child_code')},
            },
        ),
    ]
