# Generated by Django 5.0.3 on 2025-12-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_cart_add_details_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='doc_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='sales_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
