# Generated by Django 5.0.3 on 2025-12-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_cart_customer_code_cart_doc_ref_cart_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
