# Generated by Django 5.2.15 on 2026-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_cart_gross_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usd_rate', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('euro_rate', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='euro_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thai_baht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usd_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
